theme: jekyll-theme-hacker
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - SarahMatty.md
  - PatGillian.md
  - NetriGarry.md
  - FelipeRubyTheresia.md
